

name: Python application

on:
  push:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create post_traces directory
      run: mkdir -p post_traces
    - name: Lint with pylint
      run: |
        pylint *.py --exit-zero > report.txt
    - name: Error detection with pyflake
      run: |
        pyflakes *.py
    - name: Complexity analysis with radon
      run: |
        python3 -m radon cc . -s -a
        python3 -m radon mi . --json
    - name: Test with pytest
      run: |
        pytest
